name: Deploy Pages
on:
  push:
    branches: [ main ] # 推送main分支自动构建
  workflow_dispatch: # 支持手动触发
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: 安装依赖&打包
        run: npm install && npm run build
      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # vite打包输出目录
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 部署到Pages
        id: deploy
        uses: actions/deploy-pages@v4